routes/web.php
<?php
use crocodicstudio\crudbooster\controllers\AdminController as AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Admin & Superadmin
Route::prefix('admin')->group(function () {
	// Preference (Event Module)
	Route::get('event/preferences/{id}', 'AdminEventController@preferences')->name('preferences');
	Route::post('event/save-preferences/{id}', 'AdminEventController@savePreferences')->name('save-preferences');

	// Disabled Category Module
	Route::get('category_disabled/add_selected_participant', 'AdminCategoryDisabledController@addSelectedParticipant');
	Route::get('category_by_event/{event}', 'AdminCategoryDisabledController@getCategory');
	Route::get('participant_by_event_category/{event}/{category}', 'AdminCategoryDisabledController@getParticipant');
	Route::post('category_disabled/save_disabled_category', 'AdminCategoryDisabledController@saveDisabledCategory');

	// Winner Module
	Route::get('winner_by_event_category/{event}/{category}', 'AdminWinnerController@getParticipant');
	Route::post('winner/save_winner', 'AdminWinnerController@saveWinner');

	// Payment Module
	Route::get('payment/invoice/{id}', 'AdminPaymentController@printInvoice');
	Route::post('payment/save_payment', 'AdminPaymentController@savePayment');
	Route::post('payment/update_payment/{id}', 'AdminPaymentController@savePayment')->name('savePayment');
});


// Event Organizer
Route::get('', 'EOController@getLogin')->name('getLoginEO');
Route::group(['middleware' => ['eo-auth', 'eo-log'], 'prefix' => 'eo'], function () {
	Route::get('/', 'EOController@getIndex')->name('indexEO');
	Route::get('profile', 'EOController@getProfile')->name('getEOProfile');
	Route::post('profile', 'EOController@updateProfile')->name('updateProfile');
	Route::get('event_delete/{id}', 'EOEventController@destroy');
	Route::get('lockscreen', 'EOController@getLockscreen')->name('getEOLockScreen');

	// Report Module
	Route::get('detail_event/{event}', 'EOReportController@getDetail');
	Route::get('report', 'EOReportController@getIndex')->name('getEOReport');
	Route::post('report', 'EOReportController@printReport')->name('print_report');

	Route::get('dashboard_event/category_delete/{id}', 'EOCategoryController@destroy');
	Route::get('dashboard_event/participant_delete/{id}', 'EOParticipantController@destroy');
	Route::get('dashboard_event/preferences', 'EOEventController@getPreferences');

	// Draw
	Route::get('dashboard_event/draw', 'DrawController@getIndex');
	Route::get('dashboard_event/recent', 'DrawController@getRecent');
	Route::get('dashboard_event/drawing', 'DrawController@getDraw');
	Route::get('dashboard_event/winner', 'DrawController@getWinner');
	Route::get('dashboard_event/winners/{id}', 'DrawController@getWinnerByCategory');
	Route::get('dashboard_event/history', 'DrawController@getHistory');
	Route::get('dashboard_event/new', 'DrawController@getNew');

	Route::get('dashboard_event/print_invoice/{id}', 'PaymentController@printInvoice')->name('printInvoice');
	Route::get('payment/cancel/{id}', 'PaymentController@cancelTransaction');

	// Category Disabled Module// Disabled Category Module
	Route::get('dashboard_event/category_disabled', 'EOCategoryDisabledController@index');
	Route::get('dashboard_event/add_selected_participant', 'EOCategoryDisabledController@addSelectedParticipant');
	Route::get('category_by_event/{event}', 'EOCategoryDisabledController@getCategory');
	Route::get('participant_by_category/{category}', 'EOCategoryDisabledController@getParticipant');
	Route::post('category_disabled/save_disabled_category', 'EOCategoryDisabledController@saveDisabledCategory')->name('save_disabled_category');
	Route::get('enable_participant/{id}', 'EOCategoryDisabledController@enableParticipant')->name('enable_participant');

	// Participant Module
	Route::get('dashboard_event/participant/import', 'EOParticipantController@getImportView');
	Route::post('dashboard_event/participant/import', 'EOParticipantController@import')->name('importParticipant');

	// Mail to Winner
	Route::get('dashboard_event/mails', 'EOMailsController@index');
	Route::get('dashboard_event/mails/create', 'EOMailsController@create');
	Route::post('dashboard_event/mails/create', 'EOMailsController@store');
	Route::get('dashboard_event/mails/{id}', 'EOMailsController@show')->name('mails.show');

	// Resources
	Route::resources([
	    'event' => 'EOEventController',
	    'dashboard_event/category' => 'EOCategoryController',
	    'dashboard_event/participant' => 'EOParticipantController',
	    'payment' => 'PaymentController'
	]);


	Route::group(['prefix' => 'dashboard_event'], function () {
		Route::get('/{id}', 'EOEventController@dashboard');
	});
});

// Demo
Route::get('demo', 'DemoController@getIndex');
Route::get('recent', 'DemoController@getRecent');
Route::get('drawing', 'DemoController@getDraw');
Route::get('winner', 'DemoController@getWinner');
Route::get('winners', 'DemoController@getWinners');
Route::get('winners/{id}', 'DemoController@getWinnerByCategory');
Route::get('history', 'DemoController@getHistory');
Route::get('new', 'DemoController@getNew');

resources/views/event_organizer/add_category.blade.php
<!-- First you need to extend the CB layout -->
@extends('event_organizer_template.eo_template')

@section('content-header')
        <section class="content-header">
            <h1> <i class='fa fa-bars'></i> Category &nbsp;&nbsp;

              <a href="{{URL::to('eo/dashboard_event/category')}}" id='btn_show_data' class="btn btn-sm btn-primary" title="Show Data">
                  <i class="fa fa-table"></i> Show Data
              </a>

            </h1>
                <ol class="breadcrumb">
                    <li><a href="{{URL::to('eo/dashboard_event/category')}}"><i class="fa fa-bars"></i> Category</a></li>
                    <li class="active">Create</li>
                </ol>
        </section>
@endsection

@section('content')
<!-- Your custom  HTML goes here -->
<style type="text/css">
  .required{
    color: red;
    font-weight: bold;
  }
</style>

<div class='panel panel-default' id="root">
    <div class="panel-body">
        <form method="POST" action="{{URL::to('eo/dashboard_event/category')}}" id="form">
          @csrf
          <div class='form-group header-group-0 ' id='form-group-name' style="">
            <label class='control-label col-sm-2'> Category Name
                <span class='text-danger' title='This field is required'>*</span>
            </label>
            <div class="col-sm-10">
              <input type='text' title="Name" required placeholder='You can only enter the letter only'  maxlength=100 class='form-control' name="name" id="name" value=''/>

              <div class="text-danger"></div>
              <p class='help-block'></p>
            </div>
          </div>    
          <div class='form-group header-group-0 ' style="">
            <label class='control-label col-sm-2'>Total winner
              <span class='text-danger' title='This field is required'>*</span>
            </label>

            <div class="col-sm-10">
              <input type='number' title="Total Winner" required class='form-control' placeholder='You can only enter the number only' name="total_winner"/>
              <div class="text-danger"></div>
              <p class='help-block'></p>
            </div>
          </div>
   
          <input type='hidden' name="is_draw" value='0'/>
          <input type='hidden' name="event_id" value='{{Session::get("event_id")}}'/>
          <div class="col-md-12">
            <br>
            <button type="reset" class="btn btn-danger">Reset</button>
            <button type="submit" class="btn btn-success">Save Data</button>
          </div>
        </form>
    </div>
</div>
@endsection

resources/views/event_organizer/add_event.blade.php
<!-- First you need to extend the CB layout -->
@extends('event_organizer_template.eo_template')

@section('content-header')
        <section class="content-header">
            <h1> <i class='fa fa-bars'></i> Event &nbsp;&nbsp;

              <a href="{{URL::to('eo/event')}}" id='btn_show_data' class="btn btn-sm btn-primary" title="Show Data Event">
                  <i class="fa fa-table"></i> Show Data
              </a>

            </h1>
                <ol class="breadcrumb">
                    <li><a href="{{URL::to('eo/event')}}"><i class="fa fa-bars"></i> Event</a></li>
                    <li class="active">Create</li>
                </ol>
        </section>
@endsection

@section('content')
<!-- Your custom  HTML goes here -->
<style type="text/css">
  .required{
    color: red;
    font-weight: bold;
  }
</style>

<div class='panel panel-default' id="root">
    <div class="panel-body">
        <form method="POST" action="{{URL::to('eo/event')}}" id="form">
          @csrf
          <div class="col-sm-10">
          <div class='form-group header-group-0 ' id='form-group-name' style="">
            <label class='control-label col-sm-2'> Event Name
                <span class='text-danger' title='This field is required'>*</span>
            </label>
            <div class="col-sm-10">
              <input type='text' title="Name" required  placeholder='You can only enter the letter only'  maxlength=100 class='form-control' name="name" id="name" value=''/>

              <div class="text-danger"></div>
              <p class='help-block'></p>
            </div>
          </div>    
          <div class='form-group form-datepicker header-group-0 ' id='form-group-date_start' style="">
            <label class='control-label col-sm-2'>Date Start
              <span class='text-danger' title='This field is required'>*</span>
            </label>
            <div class="col-sm-4">
              <input type='date' title="Date Start" required class='form-control notfocus input_date' name="date_start" id="date_start" value='{{date("Y-m-d")}}'/>
              <div class="text-danger"></div>
              <p class='help-block'></p>
            </div>
          </div>

          <div class='form-group form-datepicker header-group-0 ' id='form-group-date_end' style="">
            <label class='control-label col-sm-2'>Date End
              <span class='text-danger' title='This field is required'>*</span>
            </label>
            <div class="col-sm-4">
              <input type='date' title="Date End" required class='form-control notfocus input_date' name="date_end" id="date_end" value='{{date("Y-m-d")}}'/>
              <div class="text-danger"></div>
              <p class='help-block'></p>
            </div>
          </div>
          </div>
          <div class="col-md-12">
            <br>
            <button type="reset" class="btn btn-danger">Reset</button>
            <button type="submit" class="btn btn-success">Save Data</button>
          </div>
        </form>
    </div>
</div>
@endsection

resources/views/event_organizer/detail_mail.blade.php
<!-- First you need to extend the CB layout -->
@extends('event_organizer_template.eo_template')

@section('content-header')
        <section class="content-header">
            <h1> <i class='fa fa-envelope'></i> Mail to Winner &nbsp;&nbsp;

              <a href="{{URL::to('eo/dashboard_event/mails')}}" id='btn_show_data' class="btn btn-sm btn-primary" title="Show Data">
                  <i class="fa fa-table"></i> Show Data
              </a>

            </h1>
                <ol class="breadcrumb">
                    <li><a href="{{URL::to('eo/dashboard_event/mails')}}"><i class="fa fa-bars"></i> Mail to Winner</a></li>
                    <li class="active">Detail</li>
                </ol>
        </section>
@endsection
@section('content')
  <!-- Your html goes here -->
  <div class='panel panel-default'>
    <div class='panel-heading'>Detail Mails</div>
    <div class='panel-body'>
      <div class="row">
        <div class='col-md-2'>
          <label>Send To</label>
        </div>
   
        <div class='col-md-10'>
          : All <strong>{{$mail->name}}</strong>'s winners
        </div>
      </div>      
      <div class="row">
        <div class='col-md-2'>
          <label>Timestamp</label>
        </div>
        <div class='col-md-10'>
          : {{date('F d, Y', strtotime($mail->created_at))}} at {{date('H:i', strtotime( $mail->created_at))}}
        </div>
      </div> 

      <div class="row">
         <div class='col-md-2'>
          <label>Content</label>
        </div>
        <div class='col-md-10'>:</div>
      </div>
      <div class="row">
         <div class='col-md-2'>
        </div>
        <div class='col-md-8 rounded' style="box-shadow: 0 0 10px #f2f2f2; border: solid 1px transparent; margin-left: 30px; padding: 25px">
          <h4><b>{{ $mail->subject }}</b></h4>
          {!! $mail->content !!}
        </div>
      </div>

    </div>
  </div>
@endsection

resources/views/event_organizer/edit_event.blade.php
<!-- First you need to extend the CB layout -->
@extends('event_organizer_template.eo_template')

@section('content-header')
        <section class="content-header">
            <h1> <i class='fa fa-bars'></i> Event &nbsp;&nbsp;

              <a href="{{URL::to('eo/event')}}" id='btn_show_data' class="btn btn-sm btn-primary" title="Show Data Event">
                  <i class="fa fa-table"></i> Show Data
              </a>

            </h1>
                <ol class="breadcrumb">
                    <li><a href="{{URL::to('eo/event')}}"><i class="fa fa-bars"></i> Event</a></li>
                    <li class="active">Edit</li>
                </ol>
        </section>
@endsection

@section('content')
<!-- Your custom  HTML goes here -->
<style type="text/css">
  .required{
    color: red;
    font-weight: bold;
  }
</style>

<div class='panel panel-default' id="root">
    <div class="panel-body">
        <form method="POST" action="{{route('event.update', $event->id)}}" id="form">
          @csrf
          @method('PUT')
          <div class="col-sm-10 text-right">
          <div class='form-group header-group-0 ' id='form-group-name' style="">
            <label class='control-label col-sm-2'> Event Name
                <span class='text-danger' title='This field is required'>*</span>
            </label>
            <div class="col-sm-10">
              <input type='text' title="Name" required  placeholder='You can only enter the letter only'  maxlength=100 class='form-control' name="name" id="name" value='{{$event->name}}'/>

              <div class="text-danger"></div>
              <p class='help-block'></p>
            </div>
          </div>    
          <div class='form-group form-datepicker header-group-0 ' id='form-group-date_start' style="">
            <label class='control-label col-sm-2'>Date Start
              <span class='text-danger' title='This field is required'>*</span>
            </label>
            <div class="col-sm-4">
              <input type='date' title="Date Start" required class='form-control notfocus input_date' name="date_start" id="date_start" value='{{$event->date_start}}'/>
              <div class="text-danger"></div>
              <p class='help-block'></p>
            </div>
          </div>

          <div class='form-group form-datepicker header-group-0 ' id='form-group-date_end' style="">
            <label class='control-label col-sm-2'>Date End
              <span class='text-danger' title='This field is required'>*</span>
            </label>
            <div class="col-sm-4">
              <input type='date' title="Date End" required class='form-control notfocus input_date' name="date_end" id="date_end" value='{{$event->date_end}}'/>
              <div class="text-danger"></div>
              <p class='help-block'></p>
            </div>
          </div>
          </div>
          <div class="col-md-12">
            <br>
            <button type="submit" class="btn btn-success">Save Data</button>
          </div>
        </form>
    </div>
</div>
@endsection

resources/views/event_organizer/event.blade.php
<!-- First you need to extend the CB layout -->
@extends('event_organizer_template.eo_template')

@section('content-header')

        <section class="content-header">
            <h1> <i class='fa fa-bars'></i> Event &nbsp;&nbsp;

              <a href="{{URL::to('eo/event')}}" id='btn_show_data' class="btn btn-sm btn-primary" title="Show Data Event">
                  <i class="fa fa-table"></i> Show Data
              </a>

              <a href="{{URL::to('eo/event/create')}}" id='btn_show_data' class="btn btn-sm btn-success" title="Add Data Event">
                  <i class="fa fa-plus-circle"></i> Add Data
              </a>

            </h1>
            <?php
            $module = CRUDBooster::getCurrentModule();
            ?>
            @if($module)
                <h1>
                    <!--Now you can define $page_icon alongside $page_tite for custom forms to follow CRUDBooster theme style -->
                    <i class='{!! ($page_icon)?:$module->icon !!}'></i> {!! ucwords(($page_title)?:$module->name) !!} &nbsp;&nbsp;

                    <!--START BUTTON -->

                    @if(CRUDBooster::getCurrentMethod() == 'getIndex')
                        @if($button_show)
                            <a href="{{ CRUDBooster::mainpath().'?'.http_build_query(Request::all()) }}" id='btn_show_data' class="btn btn-sm btn-primary"
                               title="{{cbLang('action_show_data')}}">
                                <i class="fa fa-table"></i> {{cbLang('action_show_data')}}
                            </a>
                        @endif

                        @if($button_add && CRUDBooster::isCreate())
                            <a href="{{ CRUDBooster::mainpath('add').'?return_url='.urlencode(Request::fullUrl()).'&parent_id='.g('parent_id').'&parent_field='.$parent_field }}"
                               id='btn_add_new_data' class="btn btn-sm btn-success" title="{{cbLang('action_add_data')}}">
                                <i class="fa fa-plus-circle"></i> {{cbLang('action_add_data')}}
                            </a>
                        @endif
                    @endif


                    @if($button_export && CRUDBooster::getCurrentMethod() == 'getIndex')
                        <a href="javascript:void(0)" id='btn_export_data' data-url-parameter='{{$build_query}}' title='Export Data'
                           class="btn btn-sm btn-primary btn-export-data">
                            <i class="fa fa-upload"></i> {{cbLang("button_export")}}
                        </a>
                    @endif

                    @if($button_import && CRUDBooster::getCurrentMethod() == 'getIndex')
                        <a href="{{ CRUDBooster::mainpath('import-data') }}" id='btn_import_data' data-url-parameter='{{$build_query}}' title='Import Data'
                           class="btn btn-sm btn-primary btn-import-data">
                            <i class="fa fa-download"></i> {{cbLang("button_import")}}
                        </a>
                    @endif

                <!-- END BUTTON -->
                </h1>


                <ol class="breadcrumb">
                    <li><a href="{{URL::to('eo')}}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                    <li class="active">Event</li>
                </ol>
            @else
                
            @endif
        </section>
@endsection

@section('content')
<!-- Your custom  HTML goes here -->
<div class='panel panel-default' id="root">
    <div class="panel-body">
      <table class='table table-striped table-bordered datatables-simple'>
        <thead>
            <tr>
              <th>Event Name</th>
              <th>EO User Name</th>
              <th>Status</th>
              <th>Held</th>
              <th class="text-right">Action</th>
             </tr>
        </thead>
        <tbody>
          @foreach($event as $row)
            <tr>
              <td>{{$row->name}}</td>
              <td>{{$row->user_name}}</td>
              <td>
                  <span class="label label-{{($row->status=='Active')?'success':'default'}}">
                    {{$row->status}}
                  </span>
              </td>
              <td>
                @if ($row->date_end < date("Y-m-d")) 
                  <span class='label label-default'>Past</span>
                @elseif($row->date_end == date("Y-m-d"))
                  <span class='label label-success'>Today!</span>
                @else
                  <span class='label label-info'>Upcoming</span>
                @endif
              </td>
              <td class="text-right">
                  <a class='btn btn-xs btn-info' title="Go to event's dashboard" onclick='' href="{{URL::to('eo/dashboard_event/'.$row->id)}}" target='_blank'>
                    <i class='fa fa-dashboard'></i> Dashboard
                  </a>
                <a class='btn btn-xs btn-primary btn-detail' title='Detail Data' href='{{ route('event.show', $row->id) }}'>
                  <i class='fa fa-eye'></i>
                </a>
        
                <a class='btn btn-xs btn-success btn-edit' title='Edit Data' href="{{ route('event.edit', $row->id) }}">
                  <i class='fa fa-pencil'></i>
                </a>
                <a class='btn btn-xs btn-danger btn-delete' title='Delete' href='javascript:;' 
                  onclick="swal({   
                    title: 'Are you sure ?',   
                    text: 'You will not be able to recover this record data!',   
                    type: 'warning',   
                    showCancelButton: true,   
                    confirmButtonColor: '#ff0000',   
                    confirmButtonText: 'Yes!',  
                    cancelButtonText: 'No',  
                    closeOnConfirm: false 
                  }, 
                  function(){ 
                    location.href='{{URL::to('eo/event_delete/'.$row->id)}}' 
                  });">
                    <i class='fa fa-trash'></i>
                </a>
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>
    </div>
</div>

@endsection

resources/views/event_organizer/preferences.blade.php
@extends('event_organizer_template.eo_template')

@section('content')
<style type="text/css">
  .btn-preview{
    text-align: center;
    background-color: {{($event->button_background_color=='')?'#f8514c':$event->button_background_color}};
    color: {{($event->button_text_color=='')?'#ffffff':$event->button_text_color}};
    text-transform: uppercase;
    font-size: 1.5rem;
    font-family: MontserratBold;
    padding:0.8rem 2rem;
    border: 1px solid {{($event->button_border_color=='')?'#f8514c':$event->button_border_color}};
    outline: none;
    border-radius:.4rem;
    box-shadow: 0 7px 10px 0 {{($event->button_shadow_color=='')?'#f8514c':$event->button_shadow_color}};
    -webkit-box-shadow: 0 7px 10px 0 {{($event->button_shadow_color=='')?'#f8514c':$event->button_shadow_color}};
    -moz-box-shadow: 0 7px 10px 0 {{($event->button_shadow_color=='')?'#f8514c':$event->button_shadow_color}};
    cursor: pointer;
    -webkit-transition: .3s all ease-in-out;
    -o-transition: .3s all ease-in-out;
    transition: .3s all ease-in-out; 
    margin: 1rem;
  }
  input{
    margin-top: 6px!important;
  }
  .input-preview{
    width: 100px!important;
    display: inline-block;
  }
  .preview{
    margin-left: 2.5rem;
    font-family: Montserrat;
  }
  img{
    margin-top: 5px;
    width: 100%;
  }
  .required{
    color: red;
    font-weight: bold;
  }
</style>
  
  <!-- Your html goes here -->
  <div class='panel panel-default'>
    <div class='panel-heading'>Setting Preferences</div>

    <form method="POST" action="{{route('event.update', Session::get('event_id'))}}" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class='panel-body' style="height:70%!important">
        <!-- Global Preferences -->
      <div class="col=col-md-12">
        <ul class="nav nav-tabs">
          <li class="active"><a data-toggle="tab" href="#home">Global Preference</a></li>
          <li><a data-toggle="tab" href="#menu1">New Draw Page</a></li>
          <li><a data-toggle="tab" href="#menu2">Recent Draw Page</a></li>
          <li><a data-toggle="tab" href="#menu3">Draw History Page</a></li>
        </ul>

        <div class="tab-content">
          <div id="home" class="tab-pane fade in active">
            <div class="row">
              <div class="col-md-12">
                <h3>Global Preference</h3>
              </div>
              <div class='form-group col-md-2'>
                Global Text Color<span class="required">*</span><br>
                <input type='color' name='global_text_color' required class='form-control input-preview' value="{{($event->global_text_color=='')?'#333333':$event->global_text_color}}" id="global-text-color"/>
              </div>
              <div class='form-group col-md-2'>
                Line Color<span class="required">*</span><br>
                <input type='color' name='hr_color' required class='form-control input-preview' value="{{($event->hr_color=='')?'#333333':$event->hr_color}}" id="hr-color"/>
              </div>
            </div>
            <div class="row">
              <hr>
              <div class="col-md-4 text-center">
                <div class="text-left">Preview</div><br>
                <span id="preview-global-text-color" class="pb-0 text-montserrat-bold" style="color: {{($event->global_text_color=='')?'#333333':$event->global_text_color}};">Lorem Ipsum Dolor Sit Amet</span>
                <hr id="preview-hr-color" style="margin-top:5px; border-top: 3.5px solid {{($event->hr_color=='')?'#333333':$event->hr_color}}; width:20rem;">
              </div>
            </div>
          </div>

          <div id="menu1" class="tab-pane fade">
            <!-- New Draw Page -->
            <div class="row">
              <div class="col-md-12">
                <h3>New Draw Page</h3>
              </div>
              <div class="form-group col-md-4">
                Background Image
                <input type="file" name="background_new_draw" class="form-control" accept="image/*" id="background-new-draw">
                <i><small>If the image is not set, the image will be set to the default image</small></i>
              </div>
              <div class='form-group col-md-2'>
                Button Background Color<span class="required">*</span><br>
                <input type='color' name='button_background_color' required class='form-control input-preview' value="{{($event->button_background_color=='')?'#f8514c':$event->button_background_color}}" id="button-background-color"/>
              </div>
              <div class='form-group col-md-2'>
                Button Text Color<span class="required">*</span><br>
                <input type='color' name='button_text_color' required class='form-control input-preview' value="{{($event->button_text_color=='')?'#ffffff':$event->button_text_color}}" id="button-text-color"/>
              </div>
              <div class='form-group col-md-2'>
                Button Shadow Color<span class="required">*</span><br>
                <input type='color' name='button_shadow_color' required class='form-control input-preview' value="{{($event->button_shadow_color=='')?'#f8514c':$event->button_shadow_color}}" id="button-shadow-color"/>
              </div>
              <div class='form-group col-md-2'>
                Button Border Color<span class="required">*</span><br>
                <input type='color' name='button_border_color' required class='form-control input-preview' value="{{($event->button_border_color=='')?'#f8514c':$event->button_border_color}}" id="button-border-color"/>
              </div>
            </div>

            <!-- Preview New Draw Page -->
            <div class="row">
              <hr>
              <div class="col-md-4">
                Preview
                <img id="preview-background-new-draw" alt="Uploaded Image Preview Holder" src="{{($event->background_new_draw=='')?asset('assets/background/draw_background_first.png'):asset('assets/uploads/background'.'/'.$event->background_new_draw)}}">
              </div>
              <div class="col-md-8">
                Button Preview<br>
                <button class="btn-preview" id="preview-button">New Draw</button>
              </div>
            </div>
          </div>

          <div id="menu2" class="tab-pane fade">
            <!-- Recent Draw Page -->
            <div class="row">
              <div class="col-md-12">
                <h3>Recent Draw Page</h3>
              </div>
              <div class="form-group col-md-6">
                Background
                <input type="file" name="background_recent_draw" class="form-control" accept="image/*" id="background-recent-draw">
                <i><small>If the image is not set, the image will be set to the default image</small></i>
              </div>
              <div class='form-group col-md-6'>
                Button Draw Image
                <input type="file" name="button_image" class="form-control" accept="image/*" id="button-image">
                <i><small>If the image is not set, the image will be set to the default image</small></i>
              </div>
            </div>

            <!-- Preview Recent Draw Page -->
            <div class="row">
              <hr>
              <div class="col-md-4">
                Preview
                <img id="preview-background-recent-draw" alt="Uploaded Image Preview Holder" src="{{($event->background_recent_draw=='')?asset('assets/background/draw_background_process.png'):asset('assets/uploads/background'.'/'.$event->background_recent_draw)}}">
              </div>
              <div class="col-md-2"> </div>
              <div class="col-md-2">
                Button Image Preview<br>
                <img id="preview-buton-image" alt="Uploaded Image Preview Holder" src="{{($event->button_image=='')?asset('assets/image/img_draw_button.png'):asset('assets/uploads/button'.'/'.$event->button_image)}}">
              </div>
            </div>
          </div>

          <div id="menu3" class="tab-pane fade">
            <!-- Draw History Page -->
            <div class="row">
              <div class="col-md-12">
                <h3>Draw History Page</h3>
              </div>
              <div class="form-group col-md-6">
                Background
                <input type="file" name="background_draw_history" class="form-control" accept="image/*" id="background-draw-history">
                <i><small>If the image is not set, the image will be set to the default image</small></i>
              </div>
            </div>

            <!-- Preview Draw History Page -->
            <div class="row">
              <hr>
              <div class="col-md-4">
                Preview
                <img id="preview-background-draw-history" alt="Uploaded Image Preview Holder" src="{{($event->background_draw_history=='')?asset('assets/background/draw_background_process.png'):asset('assets/uploads/background'.'/'.$event->background_draw_history)}}">
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
    <div class='panel-footer'>
      <input type='submit' class='btn btn-primary' value='Save'/>
    </div>
  </form>
  </div>

@endsection